version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$(aws ssm get-parameter --name "/osintube/ecr_repository_uri" --query "Parameter.Value" --output text)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Repository URI:" $REPOSITORY_URI
      - echo "Image tag:" $IMAGE_TAG

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --no-cache -f docker-image/Dockerfile -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Successfully pushed images:"
      - echo "  $REPOSITORY_URI:latest"
      - echo "  $REPOSITORY_URI:$IMAGE_TAG"
      - echo Configuring kubectl for sa-east-1...
      - aws eks update-kubeconfig --region sa-east-1 --name sas-6881323-eks
      - echo Restarting deployment to pull new image...
      - kubectl rollout restart deployment/osintube-app
