apiVersion: apps/v1
kind: Deployment
metadata:
  name: osintube-app
  labels:
    app: osintube
  annotations:
    keel.sh/policy: major
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 5m"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: osintube
  template:
    metadata:
      labels:
        app: osintube
    spec:
      serviceAccountName: osintube-sa
      containers:
      - name: osintube
        image: osintube-app:latest
        ports:
        - containerPort: 8501
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: SECRET_NAME
          value: "osintube-secrets"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
