[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
baseUrlPath = ""
runOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "app.dataiesb.com"

[runner]
magicEnabled = false
fastReruns = true
